export const LSP_ERROR_CODES = {
  LSP_NOT_INSTALLED: 'LSP_NOT_INSTALLED',

  LSP_TIMEOUT: 'LSP_TIMEOUT',

  LSP_INITIALIZE_FAILED: 'LSP_INITIALIZE_FAILED',

  LSP_REQUEST_FAILED: 'LSP_REQUEST_FAILED',

  LSP_EMPTY: 'LSP_EMPTY',

  LSP_CAPABILITY_UNSUPPORTED: 'LSP_CAPABILITY_UNSUPPORTED',

  LSP_FALLBACK_TO_TEXT: 'LSP_FALLBACK_TO_TEXT',

  SYMBOL_NOT_FOUND: 'SYMBOL_NOT_FOUND',

  SYMBOL_AMBIGUOUS: 'SYMBOL_AMBIGUOUS',

  UNSAFE_URI: 'UNSAFE_URI',
} as const;
