import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { allRegexPatterns } from '../src/regexes/index.js';
import { nativePatternCount } from '../src/native.js';

const __dir = dirname(fileURLToPath(import.meta.url));
const PATTERNS_RS = resolve(__dir, '..', 'src', 'patterns.rs');
const PACKAGE_JSON = resolve(__dir, '..', 'package.json');

let rsSource = '';
beforeAll(() => {
  rsSource = readFileSync(PATTERNS_RS, 'utf8');
});

describe('SYNC-01: Pattern count parity', () => {
  it('allRegexPatterns (TS source) count matches patterns.rs Pattern entries', () => {
    const rsCount = (rsSource.match(/Pattern \{ name:/g) ?? []).length;
    expect(rsCount).toBe(allRegexPatterns.length);
  });

  it('allRegexPatterns count matches nativePatternCount() (compiled binary)', () => {
    expect(nativePatternCount()).toBe(allRegexPatterns.length);
  });

  it('patterns.rs count matches nativePatternCount() (compiled binary)', () => {
    const rsCount = (rsSource.match(/Pattern \{ name:/g) ?? []).length;
    expect(rsCount).toBe(nativePatternCount());
  });
});

describe('SYNC-02: Pattern names in patterns.rs match TS canonical order', () => {
  it('every TS pattern name appears in patterns.rs', () => {
    for (const p of allRegexPatterns) {
      expect(rsSource, `missing pattern "${p.name}"`).toContain(
        `name: "${p.name}"`
      );
    }
  });

  it('names appear in the same order as allRegexPatterns', () => {
    const nameRegex = /name:\s*"([^"]+)"/g;
    const rsNames: string[] = [];
    let m: RegExpExecArray | null;
    while ((m = nameRegex.exec(rsSource)) !== null) {
      rsNames.push(m[1]!);
    }

    const tsNames = allRegexPatterns.map(p => p.name);
    expect(rsNames).toEqual(tsNames);
  });
});

describe('SYNC-03: file_context metadata parity', () => {
  it('patterns with fileContext in TS have file_context: Some(...) in patterns.rs', () => {
    const withCtx = allRegexPatterns.filter(p => p.fileContext);
    for (const p of withCtx) {
      const blockStart = rsSource.indexOf(`name: "${p.name}"`);
      expect(
        blockStart,
        `pattern "${p.name}" not found in patterns.rs`
      ).toBeGreaterThan(-1);
      const blockEnd = rsSource.indexOf('}', blockStart);
      const block = rsSource.slice(blockStart, blockEnd + 1);
      expect(
        block,
        `"${p.name}" should have file_context: Some(...)`
      ).toContain('file_context: Some(');
    }
  });

  it('patterns without fileContext in TS have file_context: None in patterns.rs', () => {
    const withoutCtx = allRegexPatterns.filter(p => !p.fileContext);
    for (const p of withoutCtx) {
      const blockStart = rsSource.indexOf(`name: "${p.name}"`);
      expect(blockStart).toBeGreaterThan(-1);
      const blockEnd = rsSource.indexOf('}', blockStart);
      const block = rsSource.slice(blockStart, blockEnd + 1);
      expect(block, `"${p.name}" should have file_context: None`).toContain(
        'file_context: None'
      );
    }
  });

  it('fileContext count matches between TS and patterns.rs', () => {
    const tsCtxCount = allRegexPatterns.filter(p => p.fileContext).length;
    const rsCtxCount = (rsSource.match(/file_context: Some\(/g) ?? []).length;
    expect(rsCtxCount).toBe(tsCtxCount);
  });
});

describe('SYNC-04: patterns.rs integrity', () => {
  it('has the DO NOT EDIT header comment', () => {
    expect(rsSource).toContain('AUTO-GENERATED by scripts/gen-patterns.mjs');
    expect(rsSource).toContain('DO NOT EDIT');
  });

  it('PATTERNS static slice length matches pattern count', () => {
    const rsCount = (rsSource.match(/Pattern \{ name:/g) ?? []).length;
    expect(rsCount).toBe(allRegexPatterns.length);
  });

  it('contains REGEX_SET builder (not missing from generation)', () => {
    expect(rsSource).toContain('RegexSetBuilder');
    expect(rsSource).toContain('REGEX_SET');
  });

  it('contains PATTERN_REGEXES lazy static (not missing from generation)', () => {
    expect(rsSource).toContain('PATTERN_REGEXES');
  });
});

describe('SYNC-05: build:ts script gate', () => {
  it('package.json build:ts script calls gen-patterns.mjs before building', () => {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, 'utf8')) as {
      scripts: Record<string, string>;
    };
    const buildTs = pkg.scripts['build:ts'] ?? '';
    expect(buildTs).toContain('gen-patterns.mjs');
    const genIdx = buildTs.indexOf('gen-patterns.mjs');
    const buildIdx = buildTs.indexOf('build.mjs');
    expect(genIdx).toBeLessThan(buildIdx);
  });

  it('build:rust script also calls gen-patterns.mjs', () => {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, 'utf8')) as {
      scripts: Record<string, string>;
    };
    const buildRust = pkg.scripts['build:rust'] ?? '';
    expect(buildRust).toContain('gen-patterns.mjs');
  });

  it('build:dev script also calls gen-patterns.mjs', () => {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, 'utf8')) as {
      scripts: Record<string, string>;
    };
    const buildDev = pkg.scripts['build:dev'] ?? '';
    expect(buildDev).toContain('gen-patterns.mjs');
  });
});
