/** Saves hand-authored public wrappers before napi-rs regenerates index.js/index.d.ts. */
'use strict'

const { copyFileSync, existsSync, readFileSync } = require('fs')
const { execFileSync } = require('child_process')
const { join } = require('path')

const root = join(__dirname, '..')

// Regenerate src/security/patterns.rs from the canonical TS pattern list before
// every native build so the Rust detector stays in lockstep with the JS fallback.
function generateSecurityPatterns() {
  execFileSync(process.execPath, [join(__dirname, 'gen-patterns.mjs')], {
    stdio: 'inherit',
    cwd: root,
  })
}

function backupPublicFile(fileName, backupName, generatedMarker) {
  const sourcePath = join(root, fileName)
  const backupPath = join(root, backupName)

  if (!existsSync(sourcePath)) return

  const source = readFileSync(sourcePath, 'utf8')
  if (source.includes(generatedMarker)) return

  copyFileSync(sourcePath, backupPath)
  console.log(`${fileName} backed up to ${backupName}`)
}

generateSecurityPatterns()

backupPublicFile('index.cjs', '.index.cjs.build-backup', 'auto-generated by NAPI-RS')
backupPublicFile('index.js', '.index.js.build-backup', 'auto-generated by NAPI-RS')
backupPublicFile('index.d.ts', '.index.d.ts.build-backup', 'auto-generated by NAPI-RS')
