/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Mask secrets in place: every even character of a matched secret is
 * replaced with `*`, preserving partial readability.
 *
 * Mirrors maskSensitiveData() from octocode-security-utils.
 */
export declare function maskSensitiveData(text: string): string

/** Returns the number of loaded patterns. */
export declare function patternCount(): number

export interface SanitizationResult {
  content: string
  hasSecrets: boolean
  secretsDetected: Array<string>
  warnings: Array<string>
}

/**
 * Detect and redact all secrets from `content`.
 * Returns the sanitized string with REDACTED placeholders, plus metadata.
 *
 * Mirrors ContentSanitizer.sanitizeContent() from octocode-security-utils.
 */
export declare function sanitizeContent(content: string, filePath?: string | undefined | null): SanitizationResult
