/* v8 ignore file -- exercised through built CLI and isolated-package subprocess tests */
export const examples = {
  memory_record: {
    agent_id: "agent",
    task_context: "task",
    observation: "lesson",
    importance: 8,
    label: "GOTCHA",
    tags: ["tag"],
    references: ["file:src/file.ts"],
    workspace_path: "/repo",
    artifact: "pkg",
    repo: "repo",
    ref: "main",
    file: "src/file.ts",
    file_tree_fingerprint: "git:HEAD",
    failure_signature: "sig",
  },
  memory_recall: {
    query: "task",
    limit: 3,
    min_importance: 4,
    labels: ["GOTCHA"],
    tags: ["tag"],
    references: ["file:src/file.ts"],
    workspace_path: "/repo",
    artifact: "pkg",
    repo: "repo",
    strict_scope: false,
    sort: "smart",
    smart: true,
  },
  workspace_status: {
    workspace: "/repo",
    artifact: "pkg",
  },
  query: {
    view: "workboard",
    query: "build",
    limit: 10,
    format: "json",
    workspace_path: "/repo",
    artifact: "pkg",
    label: ["GOTCHA"],
  },
  attend: {
    agent_id: "agent",
    query: "current task",
    limit: 10,
    workspace_path: "/repo",
    artifact: "pkg",
    file: ["src/file.ts"],
    include_bodies: false,
    explain_organ: false,
  },
  wiki_sync: {
    workspace_path: "/repo",
    out_dir: "/repo/.octocode",
    mode: "local",
    include_view: true,
    check: true,
  },
  export_harness: {
    limit: 10,
    min_importance: 7,
    workspace: "/repo",
    artifact: "pkg",
  },
  developer_review: {
    workspace: "/repo",
    format: "markdown",
  },
  session_capture: {
    agent_id: "agent",
    workspace: "/repo",
    artifact: "pkg",
    repo: "repo",
    ref: "main",
    reason: "handoff",
  },
  lock_acquire: {
    agent_id: "agent",
    workspace: "/repo",
    artifact: "pkg",
    context_ref: "docs/decision.md",
    rationale: "edit",
    target_files: ["src/file.ts", "src/file.test.ts"],
    test_plan: "test passed",
    retry_interval: 5,
    ttl_seconds: 600,
  },
  plan: {
    action: "create",
    name: "Release readiness",
    objective: "Coordinate the remaining release work.",
    lead_agent_id: "agent-lead",
    workspace: "/repo",
  },
  task: {
    action: "create",
    plan_id: "plan_abc123",
    title: "Add schema migration",
    reasoning: "Consumers need the new storage contract first.",
    acceptance: "Migration and focused tests pass.",
    path: ["src/db.ts", "tests/migration.test.ts"],
    agent_id: "agent-lead",
    priority: 10,
  },
  work: {
    action: "start",
    agent_id: "agent",
    workspace: "/repo",
    rationale: "refactor parser",
    test_plan: "run parser tests",
    target_files: ["src/parser.ts"],
    exclusive: false,
    ttl_minutes: 10,
  },
  lock_wait: {
    agent_id: "agent",
    workspace: "/repo",
    artifact: "pkg",
    target_files: ["src/file.ts"],
    wait_seconds: 120,
    retry_interval: 5,
  },
  lock_prune: {
    older_than_minutes: 20,
    expired_only: false,
    workspace: "/repo",
    artifact: "pkg",
    target_files: ["src/file.ts"],
    dry_run: true,
  },
  mine_weakness: {
    agent_id: "agent",
    workspace: "/repo",
    artifact: "pkg",
    min_count: 2,
    limit: 20,
  },
  doc_staleness: {
    targets_json: JSON.stringify([{ docFile: "docs/a.md", sourceDirs: ["src"] }]),
    workspace: "/repo",
    artifact: "pkg",
    min_edits: 5,
    min_lines: 50,
    propose: false,
  },
  docs_catalog: {
    action: "list",
  },
  digest: {
    retention_days: 90,
    refinement_handoff_retention_days: 7,
    refinement_done_retention_days: 30,
    operational_retention_days: 90,
    dry_run: true,
    workspace: "/repo",
    artifact: "pkg",
  },
  lock_release: {
    agent_id: "agent",
    run_id: "run_abc123",
    workspace: "/repo",
    artifact: "pkg",
    status: "PENDING",
  },
  verify: {
    agent_id: "agent",
    workspace: "/repo",
    artifact: "pkg",
    run_id: ["run_abc123"],
    all_pending: false,
    status: "SUCCESS",
    message: "test passed",
  },
            verify_audit: {
              agent_id: "agent",
              workspace: "/repo",
              artifact: "pkg",
            },
  forget_memory: {
    tags: ["tag"],
    workspace_path: "/repo",
    max_importance: 3,
    dry_run: true,
  },
  memory_lifecycle: {
    action: "archive",
    memory_id: ["mem_abc123"],
    workspace_path: "/repo",
    dry_run: true,
  },
  refinement: {
    agent_id: "agent",
    workspace_path: "/repo",
    artifact: "pkg",
    repo: "repo",
    ref: "main",
    files: ["src/file.ts"],
    reasoning: "handoff",
    remember: "lesson",
    quality: "handoff",
    state: "ongoing",
  },
  refine_query: {
    repo: "repo",
    ref: "main",
    quality: "handoff",
    states: ["open", "ongoing"],
    include_handoffs: true,
    include_env: false,
  },
  refine_delete: {
    refinement_id: ["ref_abc123"],
    dry_run: true,
  },
  agent_signal: {
    action: "publish",
    agent_id: "agent-a",
    to_agents: ["agent-b"],
    kind: "question",
    subject: "question",
    body: "body",
    files: ["src/file.ts"],
    artifact: "pkg",
    refs: ["task_123"],
    importance: 7,
  },
  signal_prune: {
    agent_id: "agent-a",
    resolved: true,
    older_than_days: 7,
    dry_run: true,
  },
  agent_registry: {
    action: "register",
    agent_id: "agent",
    agent_name: "Agent",
    workspace: "/repo",
    artifact: "pkg",
    context: "codex",
    limit: 50,
  },
  reflect: {
    agent_id: "agent",
    task: "task",
    outcome: "partial",
    worked: "worked",
    didnt_work: "blocked",
    judgment_note: "evidence",
    lesson: "lesson",
    fix_repo: "fix",
    fix_file: ["src/file.ts"],
    fix_instructions: "clarify when agents should install hooks",
    eval_failures: [
      {
        id: "eval-1",
        dimension: "planning",
        failure_signature: "sig",
        suggested_lesson: "lesson",
      },
    ],
    duo: true,
  },
};
