/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeLspClient {
  constructor(config: JsLanguageServerConfig)
  start(): Promise<void>
  stop(): Promise<void>
  waitForReady(timeoutMs?: number | undefined | null): Promise<void>
  hasCapability(capability: string): boolean
  getRecentStderr(): Array<string>
  openDocument(filePath: string, content: string): Promise<void>
  getDefinition(filePath: string, line: number, character: number): Promise<Array<JsCodeSnippet>>
  getReferences(filePath: string, line: number, character: number, includeDeclaration?: boolean | undefined | null): Promise<Array<JsCodeSnippet>>
  getHover(filePath: string, line: number, character: number): Promise<any>
  getTypeDefinition(filePath: string, line: number, character: number): Promise<Array<JsCodeSnippet>>
  getImplementation(filePath: string, line: number, character: number): Promise<Array<JsCodeSnippet>>
  getDocumentSymbols(filePath: string): Promise<any>
  prepareCallHierarchy(filePath: string, line: number, character: number): Promise<any>
  incomingCalls(item: any): Promise<any>
  outgoingCalls(item: any): Promise<any>
}

/**
 * Convert an LSP `SymbolKind` numeric code to a human-readable string tag
 * (e.g. `12` → `"function"`, `5` → `"class"`). Unknown codes return `"unknown"`.
 */
export declare function convertSymbolKind(kind?: number | undefined | null): string

/**
 * Return the LSP language identifier for the file at `file_path` (e.g.
 * `"typescript"`, `"python"`). Returns `null` for unrecognised extensions.
 */
export declare function detectLanguageId(filePath: string): string | null

/**
 * Convert a `file://` URI string back to an absolute filesystem path.
 *
 * # Errors
 *
 * Returns `napi::Error` when the URI is malformed or does not use the `file` scheme.
 */
export declare function fromUri(uri: string): string

/**
 * Return the default language server configuration for `file_path` inside
 * `workspace_root`. Returns `null` when no server is registered for the
 * file's language.
 */
export declare function getLanguageServerForFile(filePath: string, workspaceRoot: string): JsLanguageServerConfig | null

/**
 * Check whether `command` is available on `PATH`.
 *
 * # Errors
 *
 * Returns `napi::Error` on unexpected I/O failure during the lookup.
 */
export declare function isCommandAvailable(command: string): boolean

export interface JsCodeSnippet {
  uri: string
  range: JsRange
  content: string
  symbolKind?: string
  displayRange?: any
}

export interface JsExactPosition {
  line: number
  character: number
}

export interface JsFuzzyPosition {
  symbolName: string
  lineHint?: number
  orderHint?: number
}

export interface JsLanguageServerConfig {
  command: string
  args?: Array<string>
  workspaceRoot: string
  languageId?: string
  initializationOptions?: any
  /** Extra environment variables to inject into the language server process. */
  env?: Record<string, string>
}

export interface JsRange {
  start: JsExactPosition
  end: JsExactPosition
}

export interface JsResolvedSymbol {
  position: JsExactPosition
  foundAtLine: number
  lineOffset: number
  lineContent: string
}

/**
 * Resolve a fuzzy symbol position (name + optional line hint) to an exact
 * line/character position inside the file at `file_path`.
 *
 * # Errors
 *
 * Returns `napi::Error` when the file cannot be read or the symbol is not found.
 */
export declare function resolvePosition(filePath: string, fuzzy: JsFuzzyPosition): JsResolvedSymbol

/**
 * Resolve a fuzzy symbol position against in-memory `content` rather than
 * reading from disk. Use when the caller already holds the file text.
 *
 * # Errors
 *
 * Returns `napi::Error` when the symbol cannot be located in the content.
 */
export declare function resolvePositionFromContent(content: string, fuzzy: JsFuzzyPosition): JsResolvedSymbol

/**
 * Walk upward from `file_path` to find the workspace root (directory
 * containing a `package.json`, `.git`, or similar marker).
 *
 * # Errors
 *
 * Returns `napi::Error` when no workspace root is found above the given path.
 */
export declare function resolveWorkspaceRootForFile(filePath: string): string

/**
 * Read `file_path` from disk after canonicalizing it and confirming it is an
 * absolute regular file.
 *
 * # Errors
 *
 * Returns `napi::Error` when the file cannot be read or fails validation.
 */
export declare function safeReadFile(filePath: string): string

/**
 * Convert a human-readable symbol kind string back to the LSP `SymbolKind`
 * numeric code (e.g. `"function"` → `12`). Unknown strings return `13` (Variable).
 */
export declare function toLspSymbolKind(kind: string): number

/**
 * Convert a filesystem path to a `file://` URI string.
 *
 * # Errors
 *
 * Returns `napi::Error` when the path cannot be encoded as a valid URI.
 */
export declare function toUri(path: string): string

/**
 * Validate that `command` resolves to an executable LSP server binary.
 * Returns the resolved absolute path on success and rejects shell wrappers.
 *
 * # Errors
 *
 * Returns `napi::Error` when the command is not found or is not executable.
 */
export declare function validateLspServerPath(command: string): string
