#!/usr/bin/env node

import * as esbuild from 'esbuild';
import { execFileSync } from 'node:child_process';
import {
  chmodSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync,
  renameSync, rmSync, writeFileSync,
} from 'node:fs';
import { randomUUID } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sharedBuildOptions, coreEntryPoints, skillScriptEntries } from './buildConfig.mjs';

const packageRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(packageRoot, '../..');
const publishedOutDir = join(packageRoot, 'out');
const outDir = join(packageRoot, `.out-build-${process.pid}-${randomUUID()}`);
const legacyDistDir = join(packageRoot, 'dist');
// Staged home for standalone skill bundles. The completed tree is atomically
// promoted to out/, and every other copy derives from these generated files.
const skillScriptsOutDir = join(outDir, 'skill-scripts');
const canonicalSkillsRoot = join(repoRoot, 'skills');
const canonicalAwarenessSkill = join(canonicalSkillsRoot, 'octocode-awareness');
const canonicalAwarenessScripts = join(canonicalAwarenessSkill, 'scripts');
const agentSkillsRoot = join(repoRoot, '.agents', 'skills');
const tscBin = resolve(packageRoot, '../../node_modules/.bin/tsc');

process.chdir(packageRoot);
rmSync(outDir, { recursive: true, force: true });
rmSync(legacyDistDir, { recursive: true, force: true });
rmSync(join(packageRoot, 'skills'), { recursive: true, force: true });

const shared = sharedBuildOptions;
let published = false;

try {

// One Awareness-owned output graph. Shared domain modules become chunks; the
// schema lane stays lazy from the main CLI and carries the bundled Zod runtime.
await esbuild.build({
  ...shared,
  entryPoints: coreEntryPoints,
  outdir: outDir,
  entryNames: '[name]',
  chunkNames: 'chunks/[name]-[hash]',
  splitting: true,
  minify: true,
  logLevel: 'info',
});

// The installed Agent Skill must remain runnable after it is copied away from
// the npm package. Build standalone Awareness helpers from the same TS sources;
// no octocode CLI or tools-core source participates in these bundles. These
// land permanently under out/ — the canonical skill folder below only copies
// from here, it never generates its own copy.
rmSync(skillScriptsOutDir, { recursive: true, force: true });
mkdirSync(skillScriptsOutDir, { recursive: true });
await Promise.all(
  skillScriptEntries.map((entry) =>
    esbuild.build({
      ...shared,
      entryPoints: entry.entryPoints,
      outfile: join(skillScriptsOutDir, entry.outfileName),
      minify: true,
    })
  )
);

execFileSync(tscBin, ['--emitDeclarationOnly', '--outDir', join(outDir, 'types'), '-p', 'tsconfig.build.json'], {
  cwd: packageRoot,
  stdio: 'inherit',
});

const warningGuard = [
  '#!/usr/bin/env node',
  "process.removeAllListeners('warning');",
  "process.on('warning', (warning) => {",
  "  if (warning?.name === 'ExperimentalWarning' && String(warning?.message).includes('SQLite')) return;",
  '  console.error(warning?.stack ?? String(warning));',
  '});',
].join('\n');

function makeExecutable(path, banner = '#!/usr/bin/env node') {
  const source = readFileSync(path, 'utf8');
  writeFileSync(path, `${banner}\n${source.replace(/^#![^\n]*\n?/, '')}`);
  chmodSync(path, 0o755);
}

for (const name of ['octocode-awareness.js', 'hook-runner.js']) {
  makeExecutable(join(outDir, name), warningGuard);
}
for (const name of ['extract-hook-files.js', 'schema.js']) {
  makeExecutable(join(outDir, name));
}

// These four land in the git-tracked canonical skill (below) so an editor
// could mistake them for the hand-authored install.mjs/smoke-multi-agent.mjs
// next to them. Mark them so stray edits are not silently lost on rebuild.
const generatedNote = "// @generated by packages/octocode-awareness/build.mjs — do not edit; run `yarn build` in packages/octocode-awareness to refresh.";
for (const name of ['awareness.mjs', 'hook-runner.mjs']) {
  makeExecutable(join(skillScriptsOutDir, name), `${warningGuard}\n${generatedNote}`);
}
for (const name of ['extract-hook-files.mjs', 'schema.mjs']) {
  makeExecutable(join(skillScriptsOutDir, name), `#!/usr/bin/env node\n${generatedNote}`);
}

// Generate one static JSON Schema per Zod contract. Both the package CLI and a
// copied skill expose these exact files through `schema path <name>`.
const packageSchemaDir = join(outDir, 'schemas');
mkdirSync(packageSchemaDir, { recursive: true });
const schemaEntry = join(outDir, 'schema.js');
const schemaNames = JSON.parse(execFileSync(
  process.execPath,
  [schemaEntry, 'list', '--compact'],
  { cwd: packageRoot, encoding: 'utf8' },
));
for (const name of schemaNames) {
  const jsonSchema = JSON.parse(execFileSync(
    process.execPath,
    [schemaEntry, 'json-schema', name, '--compact'],
    { cwd: packageRoot, encoding: 'utf8' },
  ));
  const example = JSON.parse(execFileSync(
    process.execPath,
    [schemaEntry, 'example', name, '--compact'],
    { cwd: packageRoot, encoding: 'utf8' },
  ));
  jsonSchema.$id = `urn:octocode-awareness:schema:${name}`;
  jsonSchema.$comment = 'Generated by packages/octocode-awareness/build.mjs — do not edit by hand.';
  jsonSchema.examples = [example];
  writeFileSync(
    join(packageSchemaDir, `${name}.schema.json`),
    `${JSON.stringify(jsonSchema, null, 2)}\n`,
  );
}

// Refresh only generated artifacts inside the canonical Awareness skill —
// always copied *from* the permanent out/ artifacts above, never regenerated.
mkdirSync(canonicalAwarenessScripts, { recursive: true });
for (const name of [
  'awareness.mjs', 'hook-runner.mjs', 'extract-hook-files.mjs', 'schema.mjs',
]) {
  cpSync(join(skillScriptsOutDir, name), join(canonicalAwarenessScripts, name));
}
rmSync(join(canonicalAwarenessScripts, 'runtime'), { recursive: true, force: true });
rmSync(join(canonicalAwarenessScripts, 'schemas'), { recursive: true, force: true });
cpSync(packageSchemaDir, join(canonicalAwarenessScripts, 'schemas'), { recursive: true });

// Publish surface: everything ships nested under out/ — only the npm-mandated
// root files (package.json, README.md, LICENSE) live outside it.
rmSync(join(outDir, 'docs'), { recursive: true, force: true });
cpSync(join(packageRoot, 'docs'), join(outDir, 'docs'), { recursive: true });
rmSync(join(outDir, 'assets'), { recursive: true, force: true });
cpSync(join(packageRoot, 'assets'), join(outDir, 'assets'), { recursive: true });

const retiredSkills = new Set([
  'octocode-agent-communication',
  'octocode-reflection',
  'octocode-brainstorming',
  'octocode-eval',
  'octocode-prompt-optimizer',
  'octocode-rfc-generator',
  'octocode-roast',
  'octocode-skills',
  'octocode-subagent',
]);
const skipGeneratedConfig = (path) => !path.endsWith('octocode-config.mjs');
const bundledSkills = readdirSync(canonicalSkillsRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && !retiredSkills.has(entry.name))
  .filter((entry) => existsSync(join(canonicalSkillsRoot, entry.name, 'SKILL.md')))
  .map((entry) => entry.name)
  .sort();

const packagedSkillsRoot = join(outDir, 'skills');
rmSync(packagedSkillsRoot, { recursive: true, force: true });
mkdirSync(packagedSkillsRoot, { recursive: true });
mkdirSync(agentSkillsRoot, { recursive: true });

for (const skillName of retiredSkills) {
  rmSync(join(agentSkillsRoot, skillName), { recursive: true, force: true });
}
for (const skillName of bundledSkills) {
  const source = join(canonicalSkillsRoot, skillName);
  const packaged = join(packagedSkillsRoot, skillName);
  const mirrored = join(agentSkillsRoot, skillName);
  rmSync(mirrored, { recursive: true, force: true });
  cpSync(source, packaged, {
    recursive: true,
    filter: (path) => !path.includes('node_modules') && skipGeneratedConfig(path),
  });
  cpSync(source, mirrored, {
    recursive: true,
    filter: (path) => !path.includes('node_modules') && skipGeneratedConfig(path),
  });
}

// Keep the previous published tree usable until the complete replacement has
// been generated. Node does not expose rename-exchange, so publication uses a
// rollback-capable two-rename handoff with only the final filesystem swap at
// risk rather than deleting out/ at build start.
const backupOutDir = join(packageRoot, `.out-backup-${process.pid}-${randomUUID()}`);
let movedExisting = false;
try {
  if (existsSync(publishedOutDir)) {
    renameSync(publishedOutDir, backupOutDir);
    movedExisting = true;
  }
  renameSync(outDir, publishedOutDir);
  published = true;
} catch (error) {
  if (movedExisting && existsSync(backupOutDir) && !existsSync(publishedOutDir)) {
    renameSync(backupOutDir, publishedOutDir);
    movedExisting = false;
  }
  throw error;
} finally {
  if (published && movedExisting) {
    rmSync(backupOutDir, { recursive: true, force: true });
  }
}

console.log('✓ @octocodeai/octocode-awareness built → out/');
console.log(`✓ Awareness CLI → out/octocode-awareness.js (${readdirSync(join(publishedOutDir, 'chunks')).length} shared chunks)`);
console.log(`✓ generated ${schemaNames.length} standalone Zod schema files`);
console.log(`✓ bundled skills → out/skills/ (${bundledSkills.join(', ')})`);
} finally {
  if (!published) rmSync(outDir, { recursive: true, force: true });
}
