/** Saves hand-authored public wrappers before napi-rs regenerates index.js/index.d.ts. */
'use strict'

const { copyFileSync, existsSync, readFileSync } = require('fs')
const { join } = require('path')

const root = join(__dirname, '..')

function backupPublicFile(fileName, backupName, generatedMarker) {
  const sourcePath = join(root, fileName)
  const backupPath = join(root, backupName)

  if (!existsSync(sourcePath)) return

  const source = readFileSync(sourcePath, 'utf8')
  if (source.includes(generatedMarker)) return

  copyFileSync(sourcePath, backupPath)
  console.log(`${fileName} backed up to ${backupName}`)
}

backupPublicFile('index.js', 'index.public.js', 'auto-generated by NAPI-RS')
backupPublicFile('index.d.ts', 'index.public.d.ts', 'auto-generated by NAPI-RS')
